# Generated by Django 6.0.4 on 2026-05-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_2fa',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_2fa_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
