# Generated by Django 6.0.4 on 2026-05-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_annonce_image_annonce_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='nombre_pieces',
            field=models.IntegerField(blank=True, help_text='Nombre de pièces', null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='surface',
            field=models.IntegerField(blank=True, help_text='Surface en m²', null=True),
        ),
    ]
