# Generated by Django 6.0.4 on 2026-05-14 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_nombre_pieces_annonce_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='type_logement',
            field=models.CharField(choices=[('studio', 'Studio'), ('chambre', 'Chambre'), ('appartement', 'Appartement'), ('villa', 'Villa')], default='studio', max_length=20),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='nombre_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='surface',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhotoLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements/photos/')),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.annonce')),
            ],
        ),
    ]
