# Generated by Django 6.0.4 on 2026-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
